name: Killer_Bunnies
main: me.triarry.Bunnies.Bunnies
version: ${project.build.version}
author: triarry, Mammothskier

commands:
    bunnies:
        description: Shows list of commands.

permissions:
    bunnies.*:
        description: Gives all permissions.
        default: false
        children:
            bunnies.reload: true
            bunnies.debug: true
            bunnies.spawn: true
            bunnies.version: true
    bunnies.reload:
        description: Reloads the config file.
        default: false
    bunnies.debug:
        description: Shows Debug messages.
        default: false
    bunnies.spawn:
        description: Spawns a Giant at the given location.
        default: false
    bunnies.version:
        description: Displays the version of the plugin running on the server.
        default: false